### ISSUE TITLE
Repository Not Found Exception

### ISSUE THREAD

**Issue by ptarpan** [WeltN24/ecr-cleaner#15]
I need help running this on existing ECR repositories. Tried the following but keep getting an error: 

```
ecr-cleaner -aws.region=us-west-2 -repo=<repo_name> -dry-run=true 
```
```
ecr-cleaner -aws.region=us-west-2 -repo=<acct_id>.dkr.ecr.us-west-2.amazonaws.com/<repo_name> -dry-run=true
```

Error: 

```
RepositoryNotFoundException
```

What am I doing wrong?

**Comment by Mi3-14159** [comment]
Hi ptarpan,

```
ecr-cleaner -aws.region=us-west-2 -repo=<repo_name> -dry-run=true 
```
should be enough. Do your user have the permission to list ecr repositories?

**Comment by ptarpan** [comment]
hey @Mi3-14159, 
the user does indeed have permissions. Couple of questions though: 
1. We have multiple AWS accounts and so we use the `--profile` flag when using the AWS CLI. How does `ecr-cleaner` handle this? i.e. does it look for the default "profile" in `$HOME/.aws/config` or is this configurable? If the latter, how can I configure this? Here's an example to list ECR images in another account using the CLI: 
```sh
$ aws --profile <profile_name> ecr list-images --repository=<repo_name>
```
2. Considering the ECR repo can live in another AWS account, how should the `<repo_name>` value be passed? Should it be the repository ARN `arn:aws:ecr:us-west-2:<acct_id>:repository/test`, the repository URI `<acct_id>.dkr.ecr.us-west-2.amazonaws.com/test`, or just the name `test` .

**Comment by ptarpan** [comment]
@Mi3-14159 any update on the above?

**Comment by ptarpan** [comment]
Configured AWS CLI in addition to instance profiles in AWS and this is now working.
