### ISSUE TITLE
Don't reinvent the wheel

### ISSUE THREAD

**Issue by thisismana** [WeltN24/ecr-cleaner#17]
There is a perfectly good working project that covers everything this repo does: https://github.com/awslabs/ecr-cleanup-lambda

maybe put this project to rest in favor of the other project?

**Comment by stoffs** [comment]
Both projects are not needed anymore because one can clean up images with lifecycle policies in ECS. This small project was created long before this lambda existed. Greetz :)

**Comment by thisismana** [comment]
🍻
